import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Cars from '../data/cars.json'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {Cars.map(car => (
        <Link href={`${car.name}` } key={car.id}  >
          <h2 style={{cursor: 'pointer'}} > {car.name} </h2>
        </Link>
      ))}
    </div>
  )
}
